
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import static java.awt.SystemColor.menu;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class IntPrincipale extends javax.swing.JFrame {
    public String institut;

    /**
     * Creates new form IntPrincipale
     */
    public IntPrincipale() {
        initComponents();
        menu.setVisible(false);
        chercher.setVisible(false);
        supp.setVisible(false);
        maj.setVisible(false);
        ajouter.setVisible(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Institution = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        institution = new javax.swing.JComboBox<>();
        b_conf_inst = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        b_ajouter = new javax.swing.JButton();
        b_maj = new javax.swing.JButton();
        b_supp = new javax.swing.JButton();
        b_chercher = new javax.swing.JButton();
        b_sortir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        traitement = new javax.swing.JPanel();
        chercher = new javax.swing.JPanel();
        choisir_cin1 = new javax.swing.JPanel();
        choisir_nom_ch = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        b_conf_ch = new javax.swing.JButton();
        modif1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ch_nom = new javax.swing.JTextField();
        ch_prenom = new javax.swing.JTextField();
        ch_cin = new javax.swing.JTextField();
        ch_tel = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        supp = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        supp_cin = new javax.swing.JTextField();
        b_conf_supp = new javax.swing.JButton();
        b_ann_supp = new javax.swing.JButton();
        ajouter = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        a_nom = new javax.swing.JTextField();
        a_prenom = new javax.swing.JTextField();
        a_cin = new javax.swing.JTextField();
        a_tel = new javax.swing.JTextField();
        b_ann_a = new javax.swing.JButton();
        b_conf_a = new javax.swing.JButton();
        maj = new javax.swing.JPanel();
        choisir_cin = new javax.swing.JPanel();
        b_choisir_cin_maj = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        b_conf_cin_maj = new javax.swing.JButton();
        modif = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        b_modif = new javax.swing.JButton();
        b_ann_maj = new javax.swing.JButton();
        maj_nom = new javax.swing.JTextField();
        maj_prenom = new javax.swing.JTextField();
        maj_cin = new javax.swing.JTextField();
        maj_tel = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Institution.setForeground(new java.awt.Color(0, 4, 2));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Choisissez une institution");

        institution.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aucune", "FST", "ENIT", "ISI", "INSAT", "ENSIT", "ENSI" }));
        institution.setToolTipText("");
        institution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                institutionActionPerformed(evt);
            }
        });

        b_conf_inst.setText("Confirmer");
        b_conf_inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_conf_instActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InstitutionLayout = new javax.swing.GroupLayout(Institution);
        Institution.setLayout(InstitutionLayout);
        InstitutionLayout.setHorizontalGroup(
            InstitutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstitutionLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(institution, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(b_conf_inst)
                .addGap(30, 30, 30))
        );
        InstitutionLayout.setVerticalGroup(
            InstitutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstitutionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InstitutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(institution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_conf_inst))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        b_ajouter.setText("Ajouter un employé");
        b_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ajouterActionPerformed(evt);
            }
        });

        b_maj.setText("Mettre à jour un employé");
        b_maj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_majActionPerformed(evt);
            }
        });

        b_supp.setText("Supprimer un employé");
        b_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_suppActionPerformed(evt);
            }
        });

        b_chercher.setText("Chercher un employé");
        b_chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_chercherActionPerformed(evt);
            }
        });

        b_sortir.setText("Sortie");
        b_sortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sortirActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        jLabel2.setText("Menu principal:");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_supp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_maj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_chercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b_sortir))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_ajouter)
                .addGap(18, 18, 18)
                .addComponent(b_maj)
                .addGap(18, 18, 18)
                .addComponent(b_supp)
                .addGap(18, 18, 18)
                .addComponent(b_chercher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_sortir)
                .addContainerGap())
        );

        choisir_nom_ch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choisir_nom_chActionPerformed(evt);
            }
        });

        jLabel16.setText("Entrer Nom:");

        b_conf_ch.setText("Confirmer");
        b_conf_ch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_conf_chActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout choisir_cin1Layout = new javax.swing.GroupLayout(choisir_cin1);
        choisir_cin1.setLayout(choisir_cin1Layout);
        choisir_cin1Layout.setHorizontalGroup(
            choisir_cin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, choisir_cin1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(choisir_nom_ch, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(b_conf_ch)
                .addGap(23, 23, 23))
        );
        choisir_cin1Layout.setVerticalGroup(
            choisir_cin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choisir_cin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(choisir_cin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(choisir_nom_ch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_conf_ch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setText("Nom");

        jLabel19.setText("Prenom");

        jLabel20.setText("Telephone");

        jLabel21.setText("CIN");

        ch_nom.setEditable(false);

        ch_prenom.setEditable(false);

        ch_cin.setEditable(false);

        ch_tel.setEditable(false);

        javax.swing.GroupLayout modif1Layout = new javax.swing.GroupLayout(modif1);
        modif1.setLayout(modif1Layout);
        modif1Layout.setHorizontalGroup(
            modif1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modif1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(modif1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addGap(117, 117, 117)
                .addGroup(modif1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ch_tel, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(ch_cin)
                    .addComponent(ch_prenom)
                    .addComponent(ch_nom))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        modif1Layout.setVerticalGroup(
            modif1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modif1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(modif1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ch_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(modif1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ch_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modif1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ch_cin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(modif1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ch_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout chercherLayout = new javax.swing.GroupLayout(chercher);
        chercher.setLayout(chercherLayout);
        chercherLayout.setHorizontalGroup(
            chercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(choisir_cin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(modif1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator4)
        );
        chercherLayout.setVerticalGroup(
            chercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chercherLayout.createSequentialGroup()
                .addComponent(choisir_cin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modif1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel25.setText("Entrer CIN");

        b_conf_supp.setText("Confirmer");
        b_conf_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_conf_suppActionPerformed(evt);
            }
        });

        b_ann_supp.setText("Annuler");
        b_ann_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ann_suppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout suppLayout = new javax.swing.GroupLayout(supp);
        supp.setLayout(suppLayout);
        suppLayout.setHorizontalGroup(
            suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suppLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_conf_supp)
                    .addGroup(suppLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(78, 78, 78)
                        .addComponent(supp_cin, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(b_ann_supp)
                .addGap(19, 19, 19))
        );
        suppLayout.setVerticalGroup(
            suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suppLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(supp_cin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_conf_supp)
                    .addComponent(b_ann_supp))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jLabel3.setText("Entrer Nom");

        jLabel4.setText("Entrer Prenom");

        jLabel5.setText("Entrer CIN");

        jLabel6.setText("Entrer Telephone");

        a_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_prenomActionPerformed(evt);
            }
        });

        a_cin.setMaximumSize(new java.awt.Dimension(8, 8));
        a_cin.setMinimumSize(new java.awt.Dimension(8, 8));
        a_cin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_cinActionPerformed(evt);
            }
        });

        b_ann_a.setText("Annuler");
        b_ann_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ann_aActionPerformed(evt);
            }
        });

        b_conf_a.setText("Confirmer");
        b_conf_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_conf_aActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajouterLayout = new javax.swing.GroupLayout(ajouter);
        ajouter.setLayout(ajouterLayout);
        ajouterLayout.setHorizontalGroup(
            ajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterLayout.createSequentialGroup()
                .addGroup(ajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajouterLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(ajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addGroup(ajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(a_nom)
                            .addComponent(a_prenom)
                            .addComponent(a_cin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(a_tel, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                    .addGroup(ajouterLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(b_conf_a)
                        .addGap(31, 31, 31)
                        .addComponent(b_ann_a)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ajouterLayout.setVerticalGroup(
            ajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_cin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(ajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_conf_a)
                    .addComponent(b_ann_a))
                .addGap(44, 44, 44))
        );

        b_choisir_cin_maj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_choisir_cin_majActionPerformed(evt);
            }
        });

        jLabel7.setText("Entrer CIN");

        b_conf_cin_maj.setText("Confirmer");
        b_conf_cin_maj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_conf_cin_majActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout choisir_cinLayout = new javax.swing.GroupLayout(choisir_cin);
        choisir_cin.setLayout(choisir_cinLayout);
        choisir_cinLayout.setHorizontalGroup(
            choisir_cinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, choisir_cinLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(b_choisir_cin_maj, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(b_conf_cin_maj)
                .addGap(23, 23, 23))
        );
        choisir_cinLayout.setVerticalGroup(
            choisir_cinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choisir_cinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(choisir_cinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(b_choisir_cin_maj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_conf_cin_maj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Nom");

        jLabel10.setText("Prenom");

        jLabel11.setText("Telephone");

        jLabel12.setText("CIN");

        b_modif.setText("modifier");
        b_modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_modifActionPerformed(evt);
            }
        });

        b_ann_maj.setText("Annuler");
        b_ann_maj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ann_majActionPerformed(evt);
            }
        });

        maj_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maj_nomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modifLayout = new javax.swing.GroupLayout(modif);
        modif.setLayout(modifLayout);
        modifLayout.setHorizontalGroup(
            modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifLayout.createSequentialGroup()
                .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(modifLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addGap(69, 69, 69)
                        .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maj_nom)
                            .addComponent(maj_prenom)
                            .addComponent(maj_cin)
                            .addComponent(maj_tel, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(modifLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_modif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_ann_maj)))
                .addGap(20, 20, 20))
        );
        modifLayout.setVerticalGroup(
            modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(maj_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(maj_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(maj_cin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(maj_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_ann_maj)
                    .addComponent(b_modif))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout majLayout = new javax.swing.GroupLayout(maj);
        maj.setLayout(majLayout);
        majLayout.setHorizontalGroup(
            majLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(choisir_cin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(modif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator3)
        );
        majLayout.setVerticalGroup(
            majLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(majLayout.createSequentialGroup()
                .addComponent(choisir_cin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout traitementLayout = new javax.swing.GroupLayout(traitement);
        traitement.setLayout(traitementLayout);
        traitementLayout.setHorizontalGroup(
            traitementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(traitementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(traitementLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(maj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(traitementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(traitementLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(supp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
            .addGroup(traitementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(traitementLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(chercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        traitementLayout.setVerticalGroup(
            traitementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(traitementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(traitementLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(maj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(traitementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(traitementLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(supp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(22, 22, 22)))
            .addGroup(traitementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(traitementLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(chercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(22, 22, 22)))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(traitement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Institution, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Institution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(traitement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ajouterActionPerformed
        // TODO add your handling code here:
        ajouter.setVisible(true);
        chercher.setVisible(false);
        supp.setVisible(false);
        maj.setVisible(false);
    }//GEN-LAST:event_b_ajouterActionPerformed

    private void b_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_suppActionPerformed
        // TODO add your handling code here:
        chercher.setVisible(false);
        maj.setVisible(false);
        ajouter.setVisible(false);
        supp.setVisible(true);
    }//GEN-LAST:event_b_suppActionPerformed

    private void a_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_prenomActionPerformed

    private void a_cinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_cinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_cinActionPerformed

    private void b_conf_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_conf_suppActionPerformed
        // TODO add your handling code here:
       String cin=supp_cin.getText().toString();
       System.out.print(cin);
       
       
       
 
    try{
          Registry reg = LocateRegistry.getRegistry("localhost",1099); 
	  FabriqueInterface fabrique = (FabriqueInterface) 
          reg.lookup("Fabrique");
          EmployeInterface EmployeObj1;
          EmployeObj1= (EmployeInterface)fabrique.newEmploye();
         
        
          String result = EmployeObj1.DeleteEmploye(institut,cin);
  System.out.println(result);
          if(result.equals("1"))
          {
               JOptionPane.showMessageDialog(null,"ce CIN n'existe pas");
          }  
          else
          {
               JOptionPane.showMessageDialog(null," la suppression est effectuée avec succes");

          }
         
          }    
     catch (Exception e) {
	  System.out.println ("Erreur d'acces a l'objet distant.");
	  System.out.println (e.toString());
          }       
      
       
    }//GEN-LAST:event_b_conf_suppActionPerformed

    
    
    private void b_conf_instActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_conf_instActionPerformed
        // TODO add your handling code here:
        menu.setVisible(true);
    }//GEN-LAST:event_b_conf_instActionPerformed

    private void b_majActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_majActionPerformed
        // TODO add your handling code here:
        chercher.setVisible(false);
        supp.setVisible(false);
        ajouter.setVisible(false);
        maj.setVisible(true);
       modif.setVisible(false);
        
        maj_nom.setVisible(false);
        maj_prenom.setVisible(false);
        maj_cin.setVisible(false);
        maj_tel.setVisible(false);
        
    }//GEN-LAST:event_b_majActionPerformed

    private void b_chercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_chercherActionPerformed
        // TODO add your handling code here:
        supp.setVisible(false);
        maj.setVisible(false);
        ajouter.setVisible(false);
        chercher.setVisible(true);
        modif1.setVisible(false);
        
       
        
    }//GEN-LAST:event_b_chercherActionPerformed

    private void b_sortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sortirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_b_sortirActionPerformed

    private void institutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_institutionActionPerformed
       
        
      institut = institution.getSelectedItem().toString();
        // TODO add your handling code here:
    }//GEN-LAST:event_institutionActionPerformed

    private void b_conf_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_conf_aActionPerformed
        // TODO add your handling code here:
        
       String nom= a_nom.getText();
       String prenom = a_prenom.getText();
       String cin = a_cin.getText();
       String tel = a_tel.getText();
       Vector <String> result1 = new Vector <String> ();

 
    try {
          Registry reg = LocateRegistry.getRegistry("localhost",1099); 
	  FabriqueInterface fabrique = (FabriqueInterface) 
          reg.lookup("Fabrique");
          EmployeInterface EmployeObj1;
          EmployeInterface EmployeObj2;
          EmployeObj1= (EmployeInterface)fabrique.newEmploye();
          EmployeObj2= (EmployeInterface)fabrique.newEmploye();

         if (nom.isEmpty()||prenom.isEmpty()||cin.isEmpty()||tel.isEmpty())
          { JOptionPane.showMessageDialog(null,"Veuillez remplir tous les champs");  }
         else if (cin.length()!=8)
                     { JOptionPane.showMessageDialog(null,"Un CIN contient 8 chiffres");  }
  
          
          else
          {           result1 = EmployeObj2.SearchEmploye(institut,cin);
                if (result1.size()!=0)  
          {
         
            JOptionPane.showMessageDialog(null,"ce cin existe pour un autre employé");          
          }     else{

              String result = EmployeObj1.AddEmploye(institut,nom,prenom,cin,tel);

             if (result.equals("1"))
             {
                JOptionPane.showMessageDialog(null,"l'ajout est effectué avec success");
             }
         }    
          }
          }    
     catch (Exception e) {
	  System.out.println ("Erreur d'acces a l'objet distant.");
	  System.out.println (e.toString());
          }       
      

        
        
    }//GEN-LAST:event_b_conf_aActionPerformed

    private void b_conf_chActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_conf_chActionPerformed
            
          String nom=choisir_nom_ch.getText().toString();
          Vector <String> result = new Vector <String> ();

    try{
          Registry reg = LocateRegistry.getRegistry("localhost",1099); 
	  FabriqueInterface fabrique = (FabriqueInterface) 
          reg.lookup("Fabrique");
          EmployeInterface EmployeObj1;
          EmployeObj1= (EmployeInterface)fabrique.newEmploye();
         
          result = EmployeObj1.SearchName(institut,nom);
          
                            
          ch_nom.setVisible(true);
          ch_prenom.setVisible(true);
          ch_cin.setVisible(true);
          ch_tel.setVisible(true);
         
          if (result.size()!=0)    
          {
          
           
          modif1.setVisible(true);

          ch_nom.setText(result.elementAt(0));
          ch_prenom.setText(result.elementAt(1));
          ch_cin.setText(result.elementAt(2));
          ch_tel.setText(result.elementAt(3));
                
          }
          else
          {
                    JOptionPane.showMessageDialog(null,"ce nom n'existe pas");
          }
          
          }    
     catch (Exception e) {
	  System.out.println ("Erreur d'acces a l'objet distant.");
	  System.out.println (e.toString());
          }       
      
// TODO add your handling code here:
    }//GEN-LAST:event_b_conf_chActionPerformed

    private void b_conf_cin_majActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_conf_cin_majActionPerformed
        // TODO add your handling code here:
         modif.setVisible(true);
         String cin=b_choisir_cin_maj.getText().toString();
          Vector <String> result = new Vector <String> ();
          

    try{
          Registry reg = LocateRegistry.getRegistry("localhost",1099); 
	  FabriqueInterface fabrique = (FabriqueInterface) 
          reg.lookup("Fabrique");
          EmployeInterface EmployeObj1;
          EmployeObj1= (EmployeInterface)fabrique.newEmploye();
         
          result = EmployeObj1.SearchEmploye(institut,cin);
          maj_nom.setEditable(true);
          maj_prenom.setEditable(true);
          maj_cin.setEditable(true);
          maj_tel.setEditable(true);
          maj_nom.setVisible(true);
          maj_prenom.setVisible(true);
          maj_cin.setVisible(true);
          maj_tel.setVisible(true);
          maj_nom.setText(result.elementAt(0));
          maj_prenom.setText(result.elementAt(1));
          maj_cin.setText(result.elementAt(2));
          maj_tel.setText(result.elementAt(3));
                
     
          
          
          }    
     catch (Exception e) {
	  System.out.println ("Erreur d'acces a l'objet distant.");
	  System.out.println (e.toString());
          }       
    }//GEN-LAST:event_b_conf_cin_majActionPerformed

    private void b_choisir_cin_majActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_choisir_cin_majActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_choisir_cin_majActionPerformed

    private void b_ann_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ann_aActionPerformed
        // TODO add your handling code here:
        a_cin.setText("");
        a_nom.setText("");
        a_prenom.setText("");
        a_tel.setText("");
    }//GEN-LAST:event_b_ann_aActionPerformed

    private void b_ann_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ann_suppActionPerformed
        // TODO add your handling code here:
        supp_cin.setText("");
    }//GEN-LAST:event_b_ann_suppActionPerformed

    private void b_ann_majActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ann_majActionPerformed
        // TODO add your handling code here:

        maj_nom.setText("");
        maj_prenom.setText("");
        maj_cin.setText("");
        maj_tel.setText("");
    }//GEN-LAST:event_b_ann_majActionPerformed

    private void b_modifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_modifActionPerformed
         
        String cin=choisir_nom_ch.getText().toString();
        Vector <String> result = new Vector <String> ();

        try{
            Registry reg = LocateRegistry.getRegistry("localhost",1099);
            FabriqueInterface fabrique = (FabriqueInterface)
            reg.lookup("Fabrique");
            EmployeInterface EmployeObj1;
            EmployeObj1= (EmployeInterface)fabrique.newEmploye();

            result = EmployeObj1.SearchEmploye(institut,cin);
           
        }
        catch (Exception e) {
            System.out.println ("Erreur d'acces a l'objet distant.");
            System.out.println (e.toString());
        }

        // TODO add your handling code here:
        String nom=maj_nom.getText();
        if ( nom.equals("")){
            nom = result.elementAt(0);
        }

        String prenom = maj_prenom.getText();
        if ( prenom.equals("")){
            prenom = result.elementAt(1);
        }

        String cinn = maj_cin.getText();
        if ( cinn.equals("")){
            cinn = result.elementAt(2);
        }
        String tel = maj_tel.getText();
        if ( tel.equals("")){
            tel = result.elementAt(3);
        }
        System.out.println(nom+prenom+cinn+tel);
        String ch = "nom = " + nom + " ; prénom = " + prenom + " ; cin = " + cinn + " ; téléphone = " + tel;
        System.out.println(ch);
        
          try{
          Registry reg = LocateRegistry.getRegistry("localhost",1099); 
	  FabriqueInterface fabrique = (FabriqueInterface) 
          reg.lookup("Fabrique");
          
       
          
        if (cinn.length()!=8)
                     { JOptionPane.showMessageDialog(null,"Un CIN contient 8 chiffres");  }
  
          
          else
          {         
                if (result.size()!=0)  
          {
         
            JOptionPane.showMessageDialog(null,"ce cin existe pour un autre employé");          
          }     else{
                    

                    
                    
             EmployeInterface EmployeObj2;
               EmployeObj2= (EmployeInterface)fabrique.newEmploye();
               String resultat = EmployeObj2.DeleteEmploye(institut,cin); //supprimer ligne ancienne*/

               

               EmployeInterface EmployeObj3;
               EmployeObj3= (EmployeInterface)fabrique.newEmploye();
               String resultat3 = EmployeObj3.AddEmploye(institut,nom,prenom,cinn,tel); //ajouter la nouvelle ligne


               System.out.println(result);
               JOptionPane.showMessageDialog(null,"La modification est effectuée avec succès");
             
         }    
          }
         

                   
          
          
          }    
     catch (Exception e) {
	  System.out.println ("Erreur d'acces a l'objet distant.");
	  System.out.println (e.toString());
          }       
      

       
       
               //Ajouter dans la meme ligne

    }//GEN-LAST:event_b_modifActionPerformed

    private void maj_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maj_nomActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_maj_nomActionPerformed

    private void choisir_nom_chActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choisir_nom_chActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choisir_nom_chActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new IntPrincipale().setVisible(true);
                  
             
                
            }
                              
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Institution;
    private javax.swing.JTextField a_cin;
    private javax.swing.JTextField a_nom;
    private javax.swing.JTextField a_prenom;
    private javax.swing.JTextField a_tel;
    private javax.swing.JPanel ajouter;
    private javax.swing.JButton b_ajouter;
    private javax.swing.JButton b_ann_a;
    private javax.swing.JButton b_ann_maj;
    private javax.swing.JButton b_ann_supp;
    private javax.swing.JButton b_chercher;
    private javax.swing.JTextField b_choisir_cin_maj;
    private javax.swing.JButton b_conf_a;
    private javax.swing.JButton b_conf_ch;
    private javax.swing.JButton b_conf_cin_maj;
    private javax.swing.JButton b_conf_inst;
    private javax.swing.JButton b_conf_supp;
    private javax.swing.JButton b_maj;
    private javax.swing.JButton b_modif;
    private javax.swing.JButton b_sortir;
    private javax.swing.JButton b_supp;
    private javax.swing.JTextField ch_cin;
    private javax.swing.JTextField ch_nom;
    private javax.swing.JTextField ch_prenom;
    private javax.swing.JTextField ch_tel;
    private javax.swing.JPanel chercher;
    private javax.swing.JPanel choisir_cin;
    private javax.swing.JPanel choisir_cin1;
    private javax.swing.JTextField choisir_nom_ch;
    private javax.swing.JComboBox<String> institution;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel maj;
    private javax.swing.JTextField maj_cin;
    private javax.swing.JTextField maj_nom;
    private javax.swing.JTextField maj_prenom;
    private javax.swing.JTextField maj_tel;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel modif;
    private javax.swing.JPanel modif1;
    private javax.swing.JPanel supp;
    private javax.swing.JTextField supp_cin;
    private javax.swing.JPanel traitement;
    // End of variables declaration//GEN-END:variables
}
